# Generated by Django 4.1.1 on 2022-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('std', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('roll_no', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('mobile_no', models.IntegerField()),
                ('blood_group', models.CharField(max_length=3)),
            ],
        ),
    ]
